# Generated by Django 3.1.1 on 2020-09-21 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=255)),
                ('activitydate', models.DateField(default=datetime.date(2020, 9, 21))),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('activitydescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goaltext', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('projectstartdate', models.DateField()),
                ('projectenddate', models.DateField(blank=True, null=True)),
                ('projectdescription', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.category')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.goal')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetitle', models.CharField(max_length=255)),
                ('notedate', models.DateField(default=datetime.date(2020, 9, 21))),
                ('notetext', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.project')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestonename', models.CharField(max_length=255)),
                ('projecteddate', models.DateField(blank=True, null=True)),
                ('finishdate', models.DateField(blank=True, null=True)),
                ('milestonedescription', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.project')),
            ],
            options={
                'db_table': 'milestone',
            },
        ),
        migrations.CreateModel(
            name='ActivitysMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.activity')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.milestone')),
            ],
            options={
                'db_table': 'activitymilestone',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activityapp.project'),
        ),
    ]
